version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672" # RabbitMQ default AMQP port
      - "15672:15672" # RabbitMQ Management UI
    env_file:
      - .env # Reference the environment file
